# 모두를 위한 딥러닝 시즌2 - PyTorch
* Lab01-1 Tensor Manipulation 1
* https://www.youtube.com/watch?v=St7EhvnFi6c&list=PLQ28Nx3M4JrhkqBVIXg-i5_CVVoS1UzAv&index=2
----------
----------

## 1. Vector, Matrix and Tensor
### 1) vector, matrix, tensor
* Vector: 1차원
* Matrix: 2차원
* Tensor: 3차원

### 2) PyTorch Tensor Shape Convention
* 2D Tensor (Typical Simple Setting)
    * |t| = (batch size, dim)
* 3D Tensor (Typical Computer Vision)
    * |t| = (batch size, width, height)
* 3D Tensor (Typical Natural Language Processing(**NLP**))
    * |t| = (batch size, length, dim)
    * ex) 시계열

<br>
----------
-----------
## 2. Numpy Review

In [7]:
import numpy as np
import torch

### 1) 1D Array with Numpy

In [9]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [10]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  1
Shape of t:  (7,)


In [13]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])  # Element
print('t[2:5]  t[4:-1] = ', t[2:5], t[4:-1])    # Slicing
print('t[:2]     t[3:] = ', t[:2], t[3:])       # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5]  t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2]     t[3:] =  [0. 1.] [3. 4. 5. 6.]


### 2) 2D Array with Numpy

In [14]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [15]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


### 3) 1D Array with PyTorch

In [17]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [21]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 4) 2D Array with PyTorch

In [22]:
t = torch.FloatTensor([[1., 2., 3.], 
                       [4., 5., 6.], 
                       [7., 8., 9.], 
                       [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [23]:
print(t.dim())
print(t.size())
print(t[:, 1])
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


<br>
-----------
-----------
## 3. PyTorch Tensor Allocation

<br>
-----------
-----------
## 4. Matrix Mul

<br>
-----------
-----------
## 5. Other Basis Ops